tony19/vite-docs-template

- docs/.vitepress/config.ts
cherry-picked from vitejs/vite@6098457
fixes #18
> docs: fix deploy type var (#9290)

- docs/.vitepress/config.ts
cherry-picked from vitejs/vite@acc4406
fixes #19
> docs: fix deploy type var again

- docs/config/build-options.md
- docs/guide/build.md
- docs/guide/index.md
- docs/guide/migration.md
cherry-picked from vitejs/vite@b82ee5d
fixes #27
> docs: update browser baseline features (#9316)

- docs/guide/troubleshooting.md
> feat: show warning on 431 response (#9324)

- docs/config/build-options.md
- docs/config/server-options.md
Co-authored-by: Bjorn Lu <bjornlu.dev@gmail.com>
> docs: update WSL2 watch limitation explanation (#8939)

- docs/guide/troubleshooting.md
Co-authored-by: Shinigami <chrissi92@hotmail.de>
closes #66
> docs: fix typos in comments and documentation (#9711)

- docs/guide/api-javascript.md
> feat: stabilize server.resolvedUrls (#9866)

- docs/config/preview-options.md
> fix(preview): send configured headers (#9976)

- docs/config/server-options.md
> perf: cache compiled glob for `server.fs.deny` (#10044)

- docs/config/build-options.md
> feat: build.modulePreload options (#9938)

- docs/guide/api-hmr.md
Co-authored-by: Alec Larson <1925840+aleclarson@users.noreply.github.com>
Co-authored-by: 翠 / green <green@sapphi.red>
close #96
> feat: support import.meta.hot.invalidate (#10244)

- docs/guide/api-plugin.md
Co-authored-by: 翠 / green <green@sapphi.red>
close #97
> refactor(types): simplify type exports (#10243)

- docs/config/build-options.md
- docs/guide/build.md
> feat(lib): allow multiple entries (#7047)

- docs/config/build-options.md
> feat(lib): cjs instead of umd as default format for multiple entries (#10315)

- docs/guide/api-javascript.md
> feat(server): invalidate module with hmr (#10333)

- docs/guide/features.md
> feat: update esbuild compilation affecting fields (#10374)

- docs/guide/api-javascript.md
- docs/guide/api-plugin.md
> fix: expose server as Http2SecureServer type (#10196)

- docs/guide/api-javascript.md
- docs/guide/api-plugin.md
This reverts commit f328f613cccc6dda261849f4fbf1ce6041a2682b.
close #116
> chore: revert #10196 until Vite 4 (#10574)

- docs/config/build-options.md
> feat(build): experimental copyPublicDir option (#10550)

- docs/guide/features.md
> fix: tsconfig `jsx` overrides esbuild options, reverts #10374 (#10714)

- docs/guide/api-hmr.md
> feat: add `vite:afterUpdate` event (#9810)

- docs/config/server-options.md
Co-authored-by: Ben McCann <322311+benmccann@users.noreply.github.com>
close #134
> feat: base without trailing slash (#10723)

- docs/guide/api-hmr.md
> feat(hmr): invalidate message (#10946)

- docs/guide/api-hmr.md
> chore(client): expose hot.prune API (#11016)

- docs/guide/api-hmr.md
> refactor(client): simplify fetchUpdate code (#11004)

- docs/guide/api-hmr.md
> docs(api-hmr): update hot.prune docs (#11047)

- docs/guide/dep-pre-bundling.md
> feat(optimizer): support patch-package (#10286)

- docs/guide/env-and-mode.md
> fix(config)!: support development build (#11045)

- docs/guide/api-plugin.md
> feat: align object interface for `transformIndexHtml` hook (#9669)

- docs/blog/announcing-vite3.md
- docs/guide/features.md
- docs/guide/ssr.md
- docs/plugins/index.md
> refactor: move framework plugins out of core (#11158)

- docs/guide/ssr.md
> docs(guide/ssr): Fix link to react plugin repo (#11164)

- docs/guide/api-hmr.md
> chore(client)!: remove never implemented hot.decline (#11036)

- docs/.vitepress/config.ts
- docs/.vitepress/theme/components/AsideSponsors.vue
- docs/.vitepress/theme/composables/sponsor.ts
- docs/.vitepress/theme/index.ts
- docs/_data/team.js
- docs/config/build-options.md
- docs/config/dep-optimization-options.md
- docs/config/index.md
- docs/config/preview-options.md
- docs/config/server-options.md
- docs/config/shared-options.md
- docs/guide/api-hmr.md
- docs/guide/api-javascript.md
- docs/guide/api-plugin.md
- docs/guide/backend-integration.md
- docs/guide/build.md
- docs/guide/dep-pre-bundling.md
- docs/guide/features.md
- docs/guide/migration.md
- docs/guide/ssr.md
- docs/guide/using-plugins.md
> chore: enable prettier trailing commas (#11167)

- docs/guide/index.md
> feat(create-vite): add react-swc templates (#11280)

- docs/.vitepress/config.ts
- docs/blog/announcing-vite4.md
- docs/guide/migration.md
> docs: add env var section (#11286)

- docs/guide/features.md
> docs: add rationale for not type checking by default

- docs/config/preview-options.md
- docs/config/server-options.md
> feat: support BROWSER and BROWSER_ARGS in env file (#11513)

- docs/config/build-options.md
- docs/config/worker-options.md
- docs/guide/api-plugin.md
- docs/guide/build.md
- docs/guide/troubleshooting.md
> docs: update rollup docs links (#11809)

- docs/.vitepress/theme/styles/vars.css
> docs: update vitepress (#11720)

- docs/guide/troubleshooting.md
> docs: add troubleshooting for browser compat (#11877)

- docs/guide/api-plugin.md
- docs/guide/migration.md
> docs: update rollup docs links (#12130)

- docs/guide/api-hmr.md
- docs/guide/features.md
- docs/guide/index.md
- docs/guide/ssr.md
- docs/guide/static-deploy.md
related vitejs/vite@ede8bac
close #262
> docs: avoid horizontal scrollbars (#12133)

- docs/config/dep-optimization-options.md
- docs/guide/dep-pre-bundling.md
> docs(prebundling): update latest options and behaviour (#12179)

- docs/.vitepress/config.ts
- package-lock.json
- package.json
- pnpm-lock.yaml
I updated the dependencies listed inside `package.json` and
I tested the website with the new versions of the dependencies,
and since everything is working fine I thought that would be good
to pull request the updates.
> chore: update dependencies

- docs/config/server-options.md
> feat: add `sourcemapIgnoreList` configuration option (#12174)

- docs/guide/why.md
> docs: update why not esbuild (#12228)

- docs/guide/env-and-mode.md
> feat(html): support env replacement (#12202)

- docs/config/server-options.md
> docs: clarify server.sourcemapIgnoreList docs (#12325)

- docs/config/build-options.md
> feat(css): add build.cssMinify (#12207)

- docs/config/worker-options.md
> fix(worker): using data URLs for inline shared worker (#12014)

- docs/guide/api-javascript.md
- docs/guide/api-plugin.md
> feat: use preview server parameter in preview server hook (#11647)

- docs/config/shared-options.md
- docs/guide/ssr.md
> docs: fix pnpm link (#12803)

- docs/.vitepress/config.ts
- docs/releases.md
> docs: add releases page

- docs/config/dep-optimization-options.md
> docs: optimizeDeps.needsInterop (#13323)

- docs/guide/api-javascript.md
> fix(mergeConfig): don't accept callback config (#13135)

- docs/config/dep-optimization-options.md
> feat(optimizer): support glob includes (#12414)

- docs/config/server-options.md
> fix: remove deprecated config.server.base (#13482)

- docs/config/build-options.md
- docs/config/shared-options.md
- docs/guide/features.md
> docs: experimental Lightning CSS support (#13583)

- docs/.vitepress/config.ts
> docs: fix typo (#13637)

- docs/guide/features.md
> docs: fix typo (#13651)

- docs/guide/index.md
> feat(create-vite): add solidjs templates (#12218) (#12241)

- docs/guide/index.md
> docs: reference to qwik templates in getting starter guide

- docs/guide/features.md
> docs: fix build.cssMinify link (#13840)

- docs/config/build-options.md
- docs/config/dep-optimization-options.md
- docs/config/shared-options.md
- docs/config/ssr-options.md
- docs/guide/build.md
> docs: feedback about experimental features (#13846)

- docs/config/ssr-options.md
- docs/guide/ssr.md
> chore: warning about ssr cjs format removal (#13827)

- docs/.vitepress/theme/components/HomeSponsors.vue
> chore(deps): update dependency prettier to v3 (#13759)

- docs/guide/api-javascript.md
- docs/guide/api-plugin.md
> refactor!: merge `PreviewServerForHook` into `PreviewServer` type (#14119)

- docs/guide/env-and-mode.md
> docs: clarify when `import.meta.env.PROD` is `true` (#14124)

- docs/index.md
> docs: icon in ViteConf action

- docs/config/build-options.md
> feat: copyPublicDir out of experimental (#14051)

- docs/guide/index.md
> docs: remove npm@6 commands (#14240)

- docs/guide/index.md
> docs: detect Bun package manager in `create-vite` (#14017)

- docs/guide/api-javascript.md
> feat: export `server.bindCLIShortcuts` (#13675)

- docs/config/build-options.md
> feat: build.ssrEmitAssets out of experimental (#14055)

- docs/config/ssr-options.md
- docs/guide/ssr.md
> refactor: remove CJS ssr output format (#13944)

- docs/config/server-options.md
- docs/guide/api-javascript.md
> feat: allow passing down "null" to disable server watcher (#14208)

- docs/guide/features.md
> fix(deps): update all non-major dependencies (#14092)

- docs/guide/troubleshooting.md
> feat!: deprecate cjs node api (#14278)

- docs/config/server-options.md
> docs: update server.watch info

- docs/config/build-options.md
> feat(terser): add `maxWorkers` option for terserOptions (#13858)

- docs/config/build-options.md
- docs/guide/migration.md
> docs: fix typo (#14554)

- docs/guide/api-hmr.md
> feat: add off method to ViteHotContext (issue #14185) (#14518)

- docs/guide/migration.md
> fix!: return 404 for resources requests outside the base path (#5657)

- docs/guide/migration.md
> refactor!: remove exporting internal APIs (#14583)

- docs/config/server-options.md
> feat: add server.warmup option (#14291)

- docs/guide/migration.md
> feat!: rollup v4 (#14508)

- docs/guide/cli.md
- docs/guide/index.md
- docs/guide/migration.md
> refactor!: remove https flag (#14681)

- docs/guide/troubleshooting.md
> feat: postcss config `.cts` support (#14660)

- docs/config/worker-options.md
- docs/guide/migration.md
> fix!: worker.plugins is a function (#14685)

- docs/guide/migration.md
> feat!: remove ssr proxy for externalized modules (#14521)

- docs/guide/migration.md
> fix(resolve)!: remove special .mjs handling (#14723)

- docs/.vitepress/config.ts
- docs/config/server-options.md
- docs/guide/performance.md
> docs: add performance page (#14693)

- docs/config/shared-options.md
- docs/guide/migration.md
> feat(resolve)!: remove `resolve.browserField` (#14733)

- docs/config/shared-options.md
- docs/guide/migration.md
> feat(define): handle replacement with esbuild (#11151)

- docs/guide/migration.md
> refactor!: remove non boolean middleware mode (#14792)

- docs/guide/migration.md
> fix(html)!: align html serving between dev and preview (#14756)

- docs/guide/features.md
- docs/guide/migration.md
> refactor(esbuild)!: remove esbuild 0.17 -> 0.18 compat (#14804)

- docs/guide/migration.md
> refactor(preview)!: use base middleware (#14818)

- docs/config/index.md
- docs/guide/api-javascript.md
- docs/guide/migration.md
> feat!: add isPreview to ConfigEnv and resolveConfig (#14855)

- CONTRIBUTING.md
- LICENSE
- README.md
Sync with latest from `vitejs/vite`
> chore: copy LICENSE and update CONTRIBUTING/README

- docs/guide/troubleshooting.md
> feat(hmr): improve circular import updates (#14867)

- docs/config/server-options.md
- docs/guide/ssr.md
> docs(ssr): properly handle vite.middlewares after restart (#14917)

- docs/guide/api-javascript.md
> feat: allow providing parent httpServer on middleware mode (#14632)

- docs/config/shared-options.md
> fix: update type CSSModulesOptions interface (#14987)

- docs/.vitepress/buildEnd.config.ts
- docs/.vitepress/config.ts
- docs/blog/announcing-vite2.md
- docs/blog/announcing-vite3.md
- docs/blog/announcing-vite4-3.md
- docs/blog/announcing-vite4.md
- docs/blog/announcing-vite5.md
> docs: add blog rss feed on docs build (#15032)

- docs/config/server-options.md
- docs/guide/api-javascript.md
- docs/guide/ssr.md
> feat: preserve vite.middlewares connect instance after restarts (#15166)

- docs/guide/features.md
from https://github.com/vitejs/vite/commit/953e697ea43c4aad6f728d0c44f8eb74b8218d41
close #754
> feat(glob-import): deprecate as option (#14420)

- docs/config/server-options.md
> fix(hmr): make watcher ignore build.outDir (#15326)

- docs/config/ssr-options.md
> feat(ssr): support external true (#10939)

- docs/config/build-options.md
> feat: `build.assetsInlineLimit` callback (#15366)

- docs/config/dep-optimization-options.md
> refactor: remove build time pre-bundling (#15184)

- docs/guide/migration.md
> fix(deps): update all non-major dependencies (#15603)

- docs/guide/api-plugin.md
> feat: support multiple HMR clients on the server (#15340)

- docs/guide/index.md
> docs: changed bunx create-vite to bun create vite (#15646)

- docs/config/shared-options.md
> perf: use thread for preprocessors (#13584)

- docs/config/dep-optimization-options.md
> feat(optimizer): holdUntilCrawlEnd option (#15244)

- docs/.vitepress/config.ts
- docs/guide/api-vite-runtime.md
- docs/guide/ssr.md
> feat: experimental Vite Runtime API (#12165)

- docs/guide/cli.md
> refactor: remove `vite build --force` (#15837)

- docs/blog/announcing-vite5-1.md
> chore: post 5.1 release edits (#15840)

- docs/config/dep-optimization-options.md
> chore: prettier dep optimization (#15883)

- docs/config/dep-optimization-options.md
> chore: lint (#15882)

- docs/guide/ssr.md
> refactor(runtime): minor tweaks (#15904)

- docs/_data/team.js
> chore: review team members

- docs/config/shared-options.md
- docs/guide/features.md
> feat: csp nonce support (#16052)

- docs/guide/api-javascript.md
> feat: formalize waitForRequestsIdle (experimental) (#16135)

- docs/.vitepress/config.ts
- docs/.vitepress/theme/index.ts
- docs/.vitepress/tsconfig.json
- docs/config/build-options.md
- docs/config/dep-optimization-options.md
- docs/config/index.md
- docs/config/server-options.md
- docs/config/shared-options.md
- docs/guide/api-hmr.md
- docs/guide/api-javascript.md
- docs/guide/api-plugin.md
- docs/guide/assets.md
- docs/guide/backend-integration.md
- docs/guide/build.md
- docs/guide/features.md
- docs/guide/ssr.md
- docs/guide/using-plugins.md
> docs: add @shikiji/vitepress-twoslash (#16168)

- docs/guide/api-plugin.md
> docs: clarify enforce vs hook.order (#16226)

- docs/guide/backend-integration.md
> docs: fix typo (#16265)

- docs/guide/backend-integration.md
> docs: use href attribute for link with rel=modulepreload (#16279)

- docs/guide/backend-integration.md
> docs: fix capitalization typos (#16309)

- docs/guide/features.md
> feat: write cspNonce to style tags (#16419)

- docs/guide/build.md
> docs: twoslash cut does not take effect (#16466)

- docs/guide/static-deploy.md
> docs(static-deploy): add criteria comment (#16568)

- docs/.vitepress/config.ts
> docs: add meta og:site_name & update og:title

- docs/guide/api-plugin.md
> docs: deprecate server.hot (#16741)

- docs/.vitepress/buildEnd.config.ts
- docs/.vitepress/config.ts
- docs/.vitepress/theme/composables/sponsor.ts
> chore: move to eslint flat config (#16743)

- package.json
- pnpm-lock.yaml
> chore(deps): update react monorepo

- docs/config/dep-optimization-options.md
> chore: fix some comments (#17495)

- docs/guide/build.md
> docs: rename cdnjs link (#17565)

- docs/config/shared-options.md
> feat(css): support sass modern api (#17728)

- docs/.vitepress/theme/components/AsideSponsors.vue
- docs/index.md
> docs: link to ViteConf 24 (#17702)

- docs/config/server-options.md
> fix: opt-in server.fs.cachedChecks (#17807)

- docs/_data/team.js
> docs: move soda to team emiriti

- docs/_data/team.js
> chore: add hiroshi to team (#17719)
